### PR TITLE
RSS feed should use local domain (fixes #2012)

### LINKED ISSUE #2012: RSS feeds should be different for kbin communities
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

For example, the RSS feed that is linked to in https://lemmy.world/c/tech@kbin.social is https://kbin.social/feeds/m/tech.xml?sort=Active, but it should be https://kbin.social/rss?magazine=tech

### Steps to Reproduce

.

### Technical Details

.

### Lemmy Instance Version

0.18.3

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by Nutomic**
Using the remote domain doesnt work, because it may be a private instance, or may use a different software (eg Piefed or Mbin) with different RSS paths. Also checked other RSS feeds and they are already doing this correctly.

### CODE REVIEW

File: src/shared/utils/app.ts [hunk 1]
```diff
@@ -127,9 +128,13 @@ export function commentsToFlatNodes(
   return nodes;
 }
 
-export function communityRSSUrl(actorId: string, sort: string): string {
-  const url = new URL(actorId);
-  return `${url.origin}/feeds${url.pathname}.xml${getQueryString({ sort })}`;
+export function communityRSSUrl(community: Community, sort: string): string {
+  var domain = "";
```
Comment (dessalines) [inline src/shared/utils/app.ts]: Use:

`const domain = hostname(community.ap_id)`

Comment (Nutomic) [reply src/shared/utils/app.ts]: Changed

Comment (dessalines) [reply src/shared/utils/app.ts]: The community local check is pointless, just use `const domain = ...`

Comment (Nutomic) [reply src/shared/utils/app.ts]: Okay that works although it makes for longer urls.

Comment (dessalines) [reply src/shared/utils/app.ts]: Ohh ok, I guess the local check is fine there. I added it again using ternary, feel free to merge whenever.

**Review by dessalines — APPROVED** [review]
