### PR TITLE
Use http client

### LINKED ISSUE #993: Websocket closed loop issue
### Issue Summary

Hi,

I just bootstrapped a self-hosted instance through Docker following the official doc. All containers are running fine, no errors in logs. But when I open the webUI I can see in the console or in the network inspector websocket errors in loop.

Also, when I try to sign in with the admin account declared in the `lemmy.hjson`  file. When I click the "connect" button, there is no network call fired, nothing happens except the UI showing a loading spinner (I can observe the issue in Firefox and Chromium).

Basically I can't do anything in the webUI. It's quite confusing since I just followed the official “getting started” instructions.

`compose.yml` file
```
services:
  lemmy:
    image: dessalines/lemmy:latest
    container_name: lemmy
    restart: unless-stopped
    environment:
      - RUST_LOG="..."
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    ports:
      - "0.0.0.0:8536:8536"
    depends_on:
      - lemmy-db
      - pictrs
    networks:
      - lemmy

  lemmy-ui:
    image: dessalines/lemmy-ui:latest
    container_name: lemmy-ui
    restart: unless-stopped
    environment:
      LEMMY_UI_HOST: "0.0.0.0:3000"
      LEMMY_UI_LEMMY_WS_HOST: "0.0.0.0:8536"
      LEMMY_UI_LEMMY_INTERNAL_HOST: "lemmy:8536"
      LEMMY_UI_LEMMY_EXTERNAL_HOST: "localhost:3000"
      # LEMMY_UI_DISABLE_CSP: true      tried to disable it but didnt fix the issue
    ports:
      - "3003:3000"
    depends_on:
      - lemmy
    networks:
      - lemmy

  pictrs:
    image: asonix/pictrs:0.4.0-rc.1
    container_name: pictrs
    user: 1000:1000
    restart: unless-stopped
    environment:
      PICTRS__SERVER__ADDRESS: '0.0.0.0:8080'
      PICTRS__SERVER__API_KEY: xxx
    volumes:
      - ./pictrs:/mnt
    networks:
      - lemmy

  lemmy-db:
    image: postgres:15-alpine
    container_name: lemmy-db
    restart: always
    environment:
       POSTGRES_USER: lemmy
       POSTGRES_PASSWORD: xxx
       POSTGRES_DB: lemmy
    networks:
      - lemmy

networks:
  lemmy:
```

`lemmy.hjson` config
```
{
  # https://join-lemmy.org/docs/en/administration/configuration.html

  setup: {
    admin_username: "user"
    admin_password: "xxxx"
    site_name: "lemmy"
  }

  hostname: "localhost:8536" # not sure of what value is expected here
  bind: "0.0.0.0"
  port: 8536
  tls_enabled: false

  pictrs: {
    url: "http://pictrs:8080/"
    api_key: "xxx"
  }

  database: {
    database: "lemmy"
    user: "lemmy"
    password: "xxx"
    host: "lemmy-db"
    port: 5432
    pool_size: 5
  }
}
```

### Steps to Reproduce

follow the official docker install https://join-lemmy.org/docs/en/admins/install_docker.html

Launch the containers, open the web UI in the browser and observe console errors.

### Technical details

image

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
For some reason this is opening a new PR after I merged.

Closes #993.

@makotech222 This PR also fixes the edit post issue you were coming across.

### CODE REVIEW

File: src/shared/services/HttpService.ts [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+/**
+ * A Special type of apiWrapper, used only for the iso routes.
+ *
+ * Necessary because constructors can't be async
+ */
+export function apiWrapperIso<ResponseType>(
+  res: ResponseType
+): RequestState<ResponseType> {
+  try {
+    return {
```
Comment (SleeplessOne1917) [inline src/shared/services/HttpService.ts:63]: @dessalines I pointed this out on one of the draft PRs. I have no idea what error could be thrown in this try block.

File: src/shared/services/HttpService.ts [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+ *
+ * Can be empty, loading, failed, or success
+ */
+export type RequestState<T> =
+  | EmptyRequestState
+  | LoadingRequestState
+  | FailedRequestState
+  | SuccessRequestState<T>;
+
+export async function apiWrapper<ResponseType>(
```
Comment (SleeplessOne1917) [inline src/shared/services/HttpService.ts:35]: It's kind of annoying needing to use a wrapper around pretty much every call with the client. I think it might be good to move this logic into the js client project.

Comment (dessalines) [reply src/shared/services/HttpService.ts:35]: I'm still fairly torn about it. Yes its annoying, but this seems almost like application-specific logic for how to handle API state: errors, loading indicators, etc. 

It might be a bit strange to add this directly into the current API wrapper in lemmy-js-client, and have that enum variant / discriminated union be required by anyone who uses lemmy-js-client. They might have their own method of handling API state.

File: src/shared/services/HttpService.ts (hunk 1 above)
Comment (dessalines) [reply src/shared/services/HttpService.ts:63]: lemmy-js-client throws an API error, returns whatever is in the `result[error]` as a string, and this catches it, and returns a failed state with that message.

File: src/shared/components/home/site-form.tsx [hunk 3]
```diff
@@ -687,6 +689,7 @@ export class SiteForm extends Component<SiteFormProps, SiteFormState> {
             type="button"
             className="btn btn-sm bg-success ml-2"
             onClick={linkEvent(key, this.handleAddInstance)}
+            style={"width: 2rem; height: 2rem;"}
```
Comment (dessalines) [inline src/shared/components/home/site-form.tsx:692]: There's got to be some bootstrap classes for this.

File: src/shared/components/home/tagline-form.tsx [hunk 4]
```diff
@@ -1,14 +1,14 @@
...
-import { capitalizeFirstLetter, myAuth, wsClient } from "../../utils";
+import { RequestState } from "../../services/HttpService";
+import { capitalizeFirstLetter, myAuthRequired, setIsoData } from "../../utils";
 import { HtmlTags } from "../common/html-tags";
 import { Icon, Spinner } from "../common/icon";
 import { MarkdownTextArea } from "../common/markdown-textarea";
 
 interface TaglineFormProps {
-  siteRes: GetSiteResponse;
+  onSaveSite(form: EditSite): Promise<RequestState<SiteResponse>>;
```
Comment (dessalines) [inline src/shared/components/home/tagline-form.tsx:11]: Same stuff applies here. Don't have this do anything other than pass up the EditSite form.

File: src/shared/components/post/post-form.tsx [hunk 5]
```diff
@@ -51,12 +50,13 @@ const MAX_POST_TITLE_LENGTH = 200;
...
   post_view?: PostView; // If a post is given, that means this is an edit
+  crossPosts?: PostView[];
   allLanguages: Language[];
   siteLanguages: number[];
   params?: PostFormParams;
-  onCancel?(): any;
-  onCreate?(post: PostView): any;
-  onEdit?(post: PostView): any;
+  onCancel?(): void;
+  onCreate?(form: CreatePost): Promise<RequestState<PostResponse>>;
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:58]: Same stuff here. Only have this pass up the form.

Check the `CreateCommunity` page and `CommunityForm` for an example very close to this.

File: src/shared/components/post/post-form.tsx [hunk 6]
```diff
@@ -73,19 +73,19 @@ interface PostFormState {
     community_id?: number;
     honeypot?: string;
   };
-  suggestedTitle?: string;
-  suggestedPosts?: PostView[];
-  crossPosts?: PostView[];
   loading: boolean;
+  suggestedPostsRes: RequestState<SearchResponse>;
+  metadataRes: RequestState<GetSiteMetadataResponse>;
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:78]: Move these two up to the `CreatePost` page, and pass in only the suggestedposts and suggestedtitle as props.

That means this will need an `onUrlChange(string...)`, that's received by the `CreatePost` page, so it can make those requests.

File: src/shared/components/post/post-form.tsx [hunk 7]
```diff
@@ -155,49 +148,39 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
...
-
-  componentWillUnmount() {
-    this.subscription?.unsubscribe();
-    /* this.choices && this.choices.destroy(); */
-    window.onbeforeunload = null;
-  }
-
   static getDerivedStateFromProps(
-    { selectedCommunityChoice }: PostFormProps,
+    { selectedCommunityChoice, post_view }: PostFormProps,
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:152]: It would be nice if none of this were needed.

File: src/shared/components/post/post-form.tsx [hunk 8]
```diff
@@ -439,56 +415,121 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
     );
   }
 
-  handlePostSubmit(i: PostForm, event: any) {
-    event.preventDefault();
+  renderSuggestedTitleCopy() {
+    switch (this.state.metadataRes.state) {
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:419]: This also should just come from the props. Move all the API calls up to screen.

File: src/shared/components/post/post-form.tsx [hunk 9]
```diff
@@ -439,56 +415,121 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
...
+                onTransferCommunity={() => {}}
+              />
+            </>
+          )
+        );
+      }
+    }
+  }
 
+  async handlePostSubmit(i: PostForm, event: any) {
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:489]: No need for async, just set the loading = true, and  pass up the form.

File: src/shared/components/post/post-form.tsx [hunk 10]
```diff
@@ -439,56 +415,121 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
...
+        auth,
+      });
     }
+
+    i.setState({ loading: false });
   }
 
-  copySuggestedTitle(i: PostForm) {
-    let sTitle = i.state.suggestedTitle;
+  copySuggestedTitle(d: { i: PostForm; suggestedTitle?: string }) {
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:526]: This could just receive the `suggestedTitle` as a prop, and set the form.title to that.

File: src/shared/components/post/post-form.tsx [hunk 11]
```diff
@@ -501,27 +542,15 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
...
-        auth: myAuth(false),
-      };
-
-      WebSocketService.Instance.send(wsClient.search(form));
-
-      // Fetch the page title
-      getSiteMetadata(url).then(d => {
-        this.setState({ suggestedTitle: d.metadata.title });
+      this.setState({ metadataRes: { state: "loading" } });
+      this.setState({
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:549]: Move all this up a level, by adding an `onUrlChange` in the props.

File: src/shared/components/post/post-form.tsx [hunk 12]
```diff
@@ -530,23 +559,24 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
     i.fetchSimilarPosts();
   }
 
-  fetchSimilarPosts() {
+  async fetchSimilarPosts() {
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:562]: Same.

File: webpack.config.js [hunk 13]
```diff
@@ -69,10 +69,10 @@ const createServerConfig = (_env, mode) => {
...
 
   if (mode === "development") {
-    config.cache = {
-      type: "filesystem",
-      name: "server",
-    };
+    // config.cache = {
+    //   type: "filesystem",
+    //   name: "server",
+    // };
```
Comment (dessalines) [inline webpack.config.js:75]: It took a while to find these... doing `lemmy-js-client` work, using `yalc publish --push`, wasn't updating that dependency in lemmy-ui. Finally found that if I removed the entire node_modules folder, it would rebuild, then finally found that this was the culprit.

**Review by dessalines — COMMENTED** [review]
Thanks for being so fast on that merge. Ripping out websocket is pretty much our top priority, now that all lemmy instances are experiencing stability issues from tons of websocket connections.

But yeah you can see why this took me like a week and a half. Every single major component had to be reworked, the logic moved out of the components and forms, and into the top-level screens. Felt like I was doing [this](https://pbs.twimg.com/media/CIDTMo1VEAAvDg_.jpg) to lemmy-ui.

The major annoyances are:

- Having to add a ton of `this.function = this.function.bind(this)` in the constructors, and having none of them be compile-time checked. Lots of times when testing this, I'd get browser errors because I forgot to add these. 
  - React also lets you use `this` for events, even when you havent bound that event to your component. Ran into that one a lot too. Those are the only two non-compile-time-checked errors now tho, so that's nice. If when we're testing, we find errors, there's a 99% chance its one of those.
- Seemingly duplicated code, (things like `findAndUpdateComment` in the top-level screens), which set the state of lists and items based on successful API calls. 
  - It would be nice to abstract this, but only in a way that preserves the type-checking of the states.
- I didn't actually add the persisting data layer, all the data still lives and dies with the screens, but this makes that easy to add in the future.
- At some point, the PostListing and CommentNode components *should* have a limited `view_only` version, where at most you can just like, and maybe save them. As you can see right now, I made every `onXAction` prop required, so that means things like the `PostReport` component (since it shows a post), has to have a ton of unused actions like `onLockPost`. Really it should use a `PostListingViewOnly` version. That can always be done later tho.
- Immutability. As discussed we should use immutability.js for immutable lists, and anything that goes in the state. Right now react will let us alter lists in place all we want. Not a good thing for state integrity. I'll make an issue for these.

Once you fix up those three components, `PostForm`, `TaglineForm`, and `RateLimitForm`, we'll get this merged and an RC put up, so all of us can test. 

This is such a massive change, that every little bit of functionality does need to be tested rigorously.

cc @Nutomic @makotech222 

Overall tho I'm proud of getting rid of all that spaghetti code, and all the websocket annoyances.

**Review by dessalines — COMMENTED** [review]
Thanks for being so fast on that merge. Ripping out websocket is pretty much our top priority, now that all lemmy instances are experiencing stability issues from tons of websocket connections.

But yeah you can see why this took me like a week and a half. Every single major component had to be reworked, the logic moved out of the components and forms, and into the top-level screens. Felt like I was doing [this](https://pbs.twimg.com/media/CIDTMo1VEAAvDg_.jpg) to lemmy-ui.

The major annoyances are:

- Having to add a ton of `this.function = this.function.bind(this)` in the constructors, and having none of them be compile-time checked. Lots of times when testing this, I'd get browser errors because I forgot to add these. 
  - React also lets you use `this` for events, even when you havent bound that event to your component. Ran into that one a lot too. Those are the only two non-compile-time-checked errors now tho, so that's nice. If when we're testing, we find errors, there's a 99% chance its one of those.
- Seemingly duplicated code, (things like `findAndUpdateComment` in the top-level screens), which set the state of lists and items based on successful API calls. 
  - It would be nice to abstract this, but only in a way that preserves the type-checking of the states.
- I didn't actually add the persisting data layer, all the data still lives and dies with the screens, but this makes that easy to add in the future.
- At some point, the PostListing and CommentNode components *should* have a limited `view_only` version, where at most you can just like, and maybe save them. As you can see right now, I made every `onXAction` prop required, so that means things like the `PostReport` component (since it shows a post), has to have a ton of unused actions like `onLockPost`. Really it should use a `PostListingViewOnly` version. That can always be done later tho.
- Immutability. As discussed we should use immutability.js for immutable lists, and anything that goes in the state. Right now react will let us alter lists in place all we want. Not a good thing for state integrity. I'll make an issue for these.

Once you fix up those three components, `PostForm`, `TaglineForm`, and `RateLimitForm`, we'll get this merged and an RC put up, so all of us can test. 

This is such a massive change, that every little bit of functionality does need to be tested rigorously.

cc @Nutomic @makotech222 

Overall tho I'm proud of getting rid of all that spaghetti code, and all the websocket annoyances.

**Review by dessalines — COMMENTED** [review]
Thanks for being so fast on that merge. Ripping out websocket is pretty much our top priority, now that all lemmy instances are experiencing stability issues from tons of websocket connections.

But yeah you can see why this took me like a week and a half. Every single major component had to be reworked, the logic moved out of the components and forms, and into the top-level screens. Felt like I was doing [this](https://pbs.twimg.com/media/CIDTMo1VEAAvDg_.jpg) to lemmy-ui.

The major annoyances are:

- Having to add a ton of `this.function = this.function.bind(this)` in the constructors, and having none of them be compile-time checked. Lots of times when testing this, I'd get browser errors because I forgot to add these. 
  - React also lets you use `this` for events, even when you havent bound that event to your component. Ran into that one a lot too. Those are the only two non-compile-time-checked errors now tho, so that's nice. If when we're testing, we find errors, there's a 99% chance its one of those.
- Seemingly duplicated code, (things like `findAndUpdateComment` in the top-level screens), which set the state of lists and items based on successful API calls. 
  - It would be nice to abstract this, but only in a way that preserves the type-checking of the states.
- I didn't actually add the persisting data layer, all the data still lives and dies with the screens, but this makes that easy to add in the future.
- At some point, the PostListing and CommentNode components *should* have a limited `view_only` version, where at most you can just like, and maybe save them. As you can see right now, I made every `onXAction` prop required, so that means things like the `PostReport` component (since it shows a post), has to have a ton of unused actions like `onLockPost`. Really it should use a `PostListingViewOnly` version. That can always be done later tho.
- Immutability. As discussed we should use immutability.js for immutable lists, and anything that goes in the state. Right now react will let us alter lists in place all we want. Not a good thing for state integrity. I'll make an issue for these.

Once you fix up those three components, `PostForm`, `TaglineForm`, and `RateLimitForm`, we'll get this merged and an RC put up, so all of us can test. 

This is such a massive change, that every little bit of functionality does need to be tested rigorously.

cc @Nutomic @makotech222 

Overall tho I'm proud of getting rid of all that spaghetti code, and all the websocket annoyances.

File: src/shared/services/HttpService.ts (hunk 1 above)
Comment (SleeplessOne1917) [reply src/shared/services/HttpService.ts:63]: I understand, however the API call isn't being done here. The function takes an already returned response type as an argument.

**Comment by SleeplessOne1917** [comment]
@dessalines 
> Having to add a ton of this.function = this.function.bind(this) in the constructors, and having none of them be compile-time checked. Lots of times when testing this, I'd get browser errors because I forgot to add these. 

There is a way to do it without needing all the binds, but you probably won't like it. Arrow functions capture the value of this of the enclosing scope instead of having their own like ones defined with the function keyword do.

File: src/shared/services/HttpService.ts (hunk 1 above)
Comment (dessalines) [reply src/shared/services/HttpService.ts:63]: Ah I gotcha... yep the isoWrapper version since its not async (and can't be), can really only take a sucessful response.

**Comment by Nutomic** [comment]
I tried to test this but the site setup is not working. With a fresh lemmy backend it doesnt redirect to `/setup`, and opening `/setup` directly doesnt work either. Tested with latest lemmy main branch, run `./scripts/test.sh` to clear the db and reproduce.

**Comment by SleeplessOne1917** [comment]
@Nutomic how do you go through site setup when testing locally anyway? When I test locally an admin user already exists and I'm not sure if that is intentional.

**Comment by dessalines** [comment]
There's one critical bug I'll have you look at before I do an RC... the create post page. Navigating to and away from it has some weird history issues:

```
fn is not a function
at eval (webpack://lemmy-ui/./node_modules/history/index.js?:745:22)
at Array.forEach (<anonymous>)
at Object.call (webpack://lemmy-ui/./node_modules/history/index.js?:744:16)
at allowTx (webpack://lemmy-ui/./node_modules/history/index.js?:188:42)
at Object.push (webpack://lemmy-ui/./node_modules/history/index.js?:216:9)
at Object.handleClick [as event] (webpack://lemmy-ui/./node_modules/inferno-router/dist/index.esm.js?:864:15)
at dispatchEvents (webpack://lemmy-ui/./node_modules/inferno/dist/index.esm.js?:670:43)
at HTMLDocument.eval (webpack://lemmy-ui/./node_modules/inferno/dist/index.esm.js?:716:5)
```

**Comment by Nutomic** [comment]
For clarification, how are things like notification counts being updated with this change? Is there any automated polling?

**Comment by dessalines** [comment]
There's no polling in this yet, but that can always be added later.

File: src/shared/components/home/site-form.tsx (hunk 3 above)
Comment (SleeplessOne1917) [reply src/shared/components/home/site-form.tsx:651]: Unfortunately, [not out of the box](https://getbootstrap.com/docs/5.2/utilities/sizing/#relative-to-the-parent). However, [utility classes can be generated](https://getbootstrap.com/docs/5.2/utilities/api/#using-the-api).

File: src/shared/services/HttpService.ts (hunk 1 above)
Comment (SleeplessOne1917) [reply src/shared/services/HttpService.ts]: This comment change was resolved by centralizing the API wrapping logic in `HttpService.ts`.

File: src/shared/services/HttpService.ts (hunk 2 above)
Comment (SleeplessOne1917) [reply src/shared/services/HttpService.ts]: This comment change was resolved by centralizing the API wrapping logic in `HttpService.ts`.

File: src/shared/components/home/rate-limit-form.tsx [hunk 14]
```diff
@@ -23,11 +23,11 @@ interface RateLimitsProps {
 }
 
 interface RateLimitFormProps {
-  localSiteRateLimit: LocalSiteRateLimit;
-  applicationQuestion?: string;
+  onSaveSite(form: EditSite): Promise<RequestState<SiteResponse>>;
```
[the remark this answers is not in the document]
Comment (SleeplessOne1917) [reply src/shared/components/home/rate-limit-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/home/rate-limit-form.tsx [hunk 15]
```diff
@@ -105,27 +105,39 @@ function handlePerSecondChange(
   }));
 }
 
-function submitRateLimitForm(i: RateLimitsForm, event: any) {
+async function submitRateLimitForm(i: RateLimitsForm, event: any) {
```
[the remark this answers is not in the document]
Comment (SleeplessOne1917) [reply src/shared/components/home/rate-limit-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/home/rate-limit-form.tsx [hunk 16]
```diff
@@ -105,27 +105,39 @@ function handlePerSecondChange(
...
+  }
+
+  i.setState({ loading: false });
 }
 
 export default class RateLimitsForm extends Component<
   RateLimitFormProps,
   RateLimitFormState
 > {
+  private isoData = setIsoData(this.context);
```
[the remark this answers is not in the document]
Comment (SleeplessOne1917) [reply src/shared/components/home/rate-limit-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/home/site-form.tsx [hunk 17]
```diff
@@ -40,12 +42,15 @@ interface SiteFormState {
     allowed_instances: string;
     blocked_instances: string;
   };
+  siteRes: GetSiteResponse;
```
[the remark this answers is not in the document]
Comment (SleeplessOne1917) [reply src/shared/components/home/site-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/home/tagline-form.tsx (hunk 4 above)
Comment (SleeplessOne1917) [reply src/shared/components/home/tagline-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/post/post-form.tsx (hunk 5 above)
Comment (SleeplessOne1917) [reply src/shared/components/post/post-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/post/post-form.tsx (hunk 7 above)
Comment (SleeplessOne1917) [reply src/shared/components/post/post-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: src/shared/components/post/post-form.tsx (hunk 9 above)
Comment (SleeplessOne1917) [reply src/shared/components/post/post-form.tsx]: Resolved from changes merged from `use_http_client_dess`.

File: webpack.config.js (hunk 13 above)
Comment (SleeplessOne1917) [reply webpack.config.js:75]: Do you think it's worth removing completely instead of just commenting out?

File: src/shared/components/post/post-form.tsx (hunk 6 above)
Comment (SleeplessOne1917) [reply src/shared/components/post/post-form.tsx:74]: I think it's worth passing the props in as `RequestState`s so that the form can tell when to show the loading spinner.

**Comment by alectrocute** [comment]
I spent some time testing this branch out this morning and it was working great. Looking forward to seeing this merged, really excited.

**Comment by Nutomic** [comment]
Did some quick testing and it seems to work well. However new instance setup is still not working.

**Comment by SleeplessOne1917** [comment]
> Did some quick testing and it seems to work well. However new instance setup is still not working.

I won't be able to look at that until this evening when I'm back from work. If anyone wants to take a crack at fixing that beforehand, feel free.

**Comment by dessalines** [comment]
I'll do that now, and fix conflicts.

**Comment by alexmaras** [comment]
I'm trying to test this out for bugs. 

So far, I've hit 2 issues:
1. if there are no custom emojis, there's an error in the server code
2. if there are no posts, there's a JS error in the client code

I'll get a fork up and point it to this PR for the changes for you to look at. 

The second issue was caused by an invalid call to the backend. It's using `type_=2` instead of `All`, `Subscribed` or `Local`. Looking for where that is now.

**Comment by alexmaras** [comment]
actually, it appears that the `type_=2` issue persists on other devices, it's just fixed on this browser now. Seems like there's a translation from an enum and back going on but it's incorrect somewhere in the mix

**Comment by SleeplessOne1917** [comment]
@alexmaras What version are you using that you're getting `type_=2` in the query params? The JS client should be using string unions generated from rust instead of numbers.

**Comment by alexmaras** [comment]
@SleeplessOne1917
Backend: 0.17.4, docker. Was also getting the issue on 0.17.3
UI: up to date on this branch, built with `docker build`. 

Could be that it needs the absolute latest from backend? If so, I'll pull it and build the backend too to test.

**Comment by SleeplessOne1917** [comment]
Try this branch with the latest backend changes. That's what I've been doing and I haven't encountered any of the issues you mentioned.

**Comment by alexmaras** [comment]
Thanks @SleeplessOne1917, that worked. I'll check in if there are any issues. I suppose I'll close off that PR too - not sure it's necessary with updated backend. Sorry for the confusion.

**Comment by boehs** [comment]
I'd love to see a load graph after this gets merged 👀

**Comment by dessalines** [comment]
Okay, this may still have some bugs, but we can fix those now on a case by case basis to main. Its in pretty good shape. 

Major thanks to @SleeplessOne1917 for their tireless work on this.

**Comment by alectrocute** [comment]
Great work, @SleeplessOne1917!
