### PR TITLE
Fixing images being fetched at full size.

### LINKED ISSUE #3922: Full-size image displayed as thumbnail
- https://voyager.lemmy.ml/post/34021
- https://voyager.lemmy.ml/post/34013

Thumbnails are rendered at 80x80 pixels. Yet lemmy-ui downloads the full image with 1000x1000 pixels or more. Problem occurs both for local uploads and proxied images.

### PR DESCRIPTION
**Pull request by dessalines**
- This ensures that all post images (proxied, thumbnails, or full size), uses the correct `max_size` param in the lemmy backend (it was called `thumbnail` before), so that smaller images are fetched.
  - Icons are 96px, thumbnails are 256px, and full cards are 512px.
- Also removes any of the format conversions, and just lets them be viewed in the original format.
- For viewerjs, it removes the `max_size` param, so that when clicked, it views full size images.
- This also works for images in markdown bodies now, which use the `thumbnail` size by default (and can be clicked into to show the full size).
- Requires https://github.com/LemmyNet/lemmy/pull/6369
- Fixes #3922

### CODE REVIEW

File: src/shared/components/common/pictrs-image.tsx [hunk 1]
```diff
@@ -147,7 +143,7 @@ export class PictrsImage extends Component<Props, State> {
     );
   }
 
-  src(format: string): string {
+  src(): string {
```
Comment (dessalines) [inline src/shared/components/common/pictrs-image.tsx]: ~~Might need to externalize this function so that it can be used with markdown images.~~

**Comment by Nutomic** [comment]
Tried to view the posts in the linked issue with your changes, in both cases the thumbnails fail to load.
- In case of `/post/34021` it attempts to load https://voyager.lemmy.ml/api/v4/image/02d0cca5-bf6e-4264-bba2-9f58c9998aff.jpeg?max_size=256 which fails. This should be fixed by https://github.com/LemmyNet/lemmy/pull/6369.
- And in case of `/post/34013` it loads https://voyager.lemmy.ml/api/v4/image/proxy?url=https://i0.wp.com/dbzer0.com/wp-content/uploads/2025/12/small3-1.png?resize=980%2C980&ssl=1&max_size=256 which is invalid with two times `?` (needs urlencode for url param)
    ```json
    {"error":"not_found","cause":"NotFound"}
    ```

Fullsize images are both working.

**Comment by dessalines** [comment]
Both those are dependent on https://github.com/LemmyNet/lemmy/pull/6369 which isn't deployed to voyager.lemmy.ml 's backend yet. Should be testable tomorrow.

**Comment by Nutomic** [comment]
Both of the posts look good now, only small thumbnails are loaded. Urlencode is also fine, just the browser decodes it before rendering which was confusing.
