### PR TITLE
Dont hide reply box on other actions. Fixes #1968

### LINKED ISSUE #1968: Voting on a comment discards the comment you are typing
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Voting on posts closes the comment form, losing whatever you've typed.

### Steps to Reproduce

1. Start typing a reply to a comment. Don't submit it yet.
2. Upvote a comment while your reply is insubmitted. It doesn't seem to matter if I upvote the comment I was reply to or a different one.
3. The reply I was typing is now lost. The text area was discarded and reopening the reply form has the text area open again, forcing me to rewrite my entire comment.

### Technical Details

Noticed this in mobile Chrome (114.0.5735.196) on lemm.ee with Android 13, Samsung s23 ultra. Haven't checked if anything else is affected.

### Lemmy Instance Version

0.18.2 (backend, couldn't tell where it says the front-end version)

### Lemmy Instance URL

lemme.ee

### PR DESCRIPTION
**Pull request by dessalines**
## Description

Fixes an issue with comment actions "finishing" / closing the reply box

### After

https://github.com/LemmyNet/lemmy-ui/assets/930215/0f3a37b4-7b61-46a6-8c23-421bce7c6950

### CODE REVIEW

File: src/shared/components/post/post.tsx [hunk 1]
```diff
@@ -1072,6 +1072,19 @@ export class Post extends Component<any, PostState> {
...
 
+  // No need to set finished on a comment vote, save, etc
+  findAndUpdateComment(res: RequestState<CommentResponse>) {
+    this.setState(s => {
+      if (s.commentsRes.state === "success" && res.state === "success") {
+        s.commentsRes.data.comments = editComment(
+          res.data.comment_view,
+          s.commentsRes.data.comments,
+        );
+      }
```
Comment (dessalines) [inline src/shared/components/post/post.tsx:1083]: The main was on `L1069` with `s.finished.set` 

It should only "finish" the comment (IE clear the reply / edit box), on either an edit or a comment create. It shouldn't close the box on a vote, save, etc. 

So I just had to create `findAndUpdateCommentEdit` alternatives that included the finished setting, and remove the finished on the existing ones.
