### PR TITLE
Filter community selection for posting (fixes #2604)

### LINKED ISSUE #2604: no error displayed when posting to a mods-only community
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

trying to post to `!retrogaming@lemmy.zip` https://lemmy.zip/c/retrogaming

I get the spinner on the post button but it never finishes or reports anything. So I opened the devtools and saw the result of the call

```
{"error":"only_mods_can_post_in_community"}
```

### Steps to Reproduce

1. post to `!retrogaming@lemmy.zip`
2. see it fail

### Technical Details

Chrome Win10

### Lemmy Instance Version

0.19.3

### Lemmy Instance URL

https://programming.dev/

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: src/shared/components/post/post-form.tsx [hunk 1]
```diff
@@ -954,3 +960,21 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
...
+  const follows = my_user?.follows.map(c => c.community.id);
+  return (
+    comms
+      // filter out comms where only mods can post, unless current user is mod
+      .filter(c => !c.community.posting_restricted_to_mods || c.can_mod)
+      // filter out private comms unless the current user follows it
+      .filter(
+        c =>
+          c.community.visibility !== "Private" ||
+          follows?.includes(c.community.id),
```
Comment (dessalines) [inline src/shared/components/post/post-form.tsx:976]: Doesn't the follow state have to be approved? IE you can be trying to follow a private community, and `Pending` will come back in your follow list.

Comment (Nutomic) [reply src/shared/components/post/post-form.tsx:976]: I added a backend filter for that: https://github.com/LemmyNet/lemmy/pull/6003/files#diff-4f4537d4bbffbcd3b0a6f0bb920ffb8439ba34f77017b89ebe6291190413ac2aR82

Comment (dessalines) [reply src/shared/components/post/post-form.tsx:976]: That filter would still bring back follows with the `Denied` state. That's the danger of just using `includes` instead of checking for the `Accepted` state.

Comment (Nutomic) [reply src/shared/components/post/post-form.tsx:976]: Changed the backend PR to exclude `Denied` as well. After all these shouldnt be listed in the sidebar as followed either. However `Pending` is fine to be included.

File: src/shared/components/post/post-form.tsx [hunk 2]
```diff
@@ -932,7 +932,13 @@ export class PostForm extends Component<PostFormProps, PostFormState> {
...
 
     if (text.length > 0) {
-      newOptions.push(...(await fetchCommunities(text)).map(communityToChoice));
+      newOptions.push(
+        ...filterCommunitySelection(
+          await fetchCommunities(text),
+          this.props.myUserInfo,
+        ).map(communityToChoice),
+      );
+      console.log(newOptions);
```
Comment (SleeplessOne1917) [inline src/shared/components/post/post-form.tsx]: Was this just put in for testing your changes? If so, don't forget to remove.

Comment (Nutomic) [reply src/shared/components/post/post-form.tsx]: Fixed

**Review by SleeplessOne1917 — APPROVED** [review]
