### PR TITLE
Post title on listing page should always open comments (fixes #3755)

### LINKED ISSUE #3755: [1.0] Clicking title of image post opens the image url instead of comments
### Requirements

- [x] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [x] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [x] It's a single bug. Do not report multiple bugs in one issue.
- [x] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

You can test it here: https://voyager.lemmy.ml/u/thelsim@sh.itjust.works

With 0.19 clicking the title of a post always opens the post page with comments. With 1.0, only for image posts it opens the image url instead.

### Lemmy Instance Version

1.0

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: src/shared/components/post/common.tsx [hunk 1]
```diff
@@ -34,12 +33,9 @@ type PostNameProps = {
 export function PostName({ post, showBody }: PostNameProps) {
   const url = post.url;
 
-  // Only navigate to external, if its media, or the full post
-  const navigateExternal = (url && isMedia(url)) || showBody === "full";
-
   return (
     <h1 className="post-name h5 d-inline text-break">
-      {navigateExternal ? (
```
Comment (dessalines) [inline src/shared/components/post/common.tsx:42]: Just get of this function then, since its only used here.

Comment (Nutomic) [reply src/shared/components/post/common.tsx:42]: What do you mean?

Comment (dessalines) [reply src/shared/components/post/common.tsx:42]: Delete the `navigateExternal` function, its only used in one place, and now that's gone.

Comment (Nutomic) [reply src/shared/components/post/common.tsx:42]: Its not a function but a variable, and its already removed.

Comment (dessalines) [reply src/shared/components/post/common.tsx:42]: Whoops sry, brainfart.
