### PR TITLE
Fix bug where newly created communities cannot be edited until refresh

### LINKED ISSUE #2442: Mod actions not available until reload when creating a new community
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When creating a new community, lemmy-ui does not recognize me as moderator and won't allow me to perform moderator actions on the new community until I reload the page.
This includes actions like editing the community or locking/featuring posts in the community.

### Steps to Reproduce

1. Create a new community
2. Do not reload the page

### Technical Details

image
image

### Lemmy Instance Version

0.19.4-beta.5

### Lemmy Instance URL

https://voyager.lemmy.ml

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Closes #2442

### CODE REVIEW

File: src/shared/components/community/create-community.tsx [hunk 1]
```diff
@@ -68,6 +68,11 @@ export class CreateCommunity extends Component<
     const res = await HttpService.client.createCommunity(form);
 
     if (res.state === "success") {
+      const myUser = UserService.Instance.myUserInfo!;
+      UserService.Instance.myUserInfo?.moderates.push({
+        community: res.data.community_view.community,
+        moderator: myUser.local_user_view.person,
+      });
```
Comment (SleeplessOne1917) [inline src/shared/components/community/create-community.tsx:75]: This is a kludge, but there isn't a better way to do it in this codebase at the moment.

**Review by dessalines — APPROVED** [review]
