### PR TITLE
fix: Fix bug where user could not block person from profile page

### LINKED ISSUE #2149: Cannot unblock user from profile page
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you have a user blocked and go to their profile page, the button will still say block, and clicking it will not unblock the user. Unblocking on the settings page still works.

### Steps to Reproduce

1. Block user on their profile page
2. Refresh
3. Notice that button still says block.

### Technical Details

n/a

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

https://lemmygrad.ml

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Resolves #2149

### CODE REVIEW

File: src/shared/components/person/profile.tsx [hunk 1]
```diff
@@ -155,6 +155,13 @@ const Moderates = ({ moderates }: { moderates?: CommunityModeratorView[] }) =>
 const Follows = () =>
   getCommunitiesListing("subscribed", UserService.Instance.myUserInfo?.follows);
 
+const isPersonBlocked = (personRes: RequestState<GetPersonDetailsResponse>) =>
```
Comment (dessalines) [inline src/shared/components/person/profile.tsx:158]: These are functions, not constants.

File: src/shared/components/person/profile.tsx [hunk 2]
```diff
@@ -826,6 +824,7 @@ export class Profile extends Component<
     const blockPersonRes = await HttpService.client.blockPerson(form);
     if (blockPersonRes.state === "success") {
       updatePersonBlock(blockPersonRes.data);
```
Comment (dessalines) [inline src/shared/components/person/profile.tsx:826]: Having this in state is much cleaner, thx.

**Review by dessalines — APPROVED** [review]
