### PR TITLE
Clicking "subscribe pending" button performs unsubscribe (fixes #705)

### LINKED ISSUE #705: Allow unfollowing a community while status is "pending"
In case a follow failed to go through, it would be useful to be able to cancel it, and try again. This could be implemented simply by turning the "subscribe pending" text into a button, which does unfollow when clicked.

Screenshot_20220630_120029

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: src/shared/components/community/sidebar.tsx [hunk 1]
```diff
@@ -130,9 +130,13 @@ export class Sidebar extends Component<SidebarProps, SidebarState> {
             </a>
           )}
           {subscribed == SubscribedType.Pending && (
-            <div class="badge badge-warning mr-2">
+            <a
+              class="badge badge-warning mr-2"
```
Comment (dessalines) [inline src/shared/components/community/sidebar.tsx:134]: Could you turn this into a `btn btn-warning`

Comment (Nutomic) [reply src/shared/components/community/sidebar.tsx]: I changed the class, but dont understand what you mean by removing <a> tag. The previous item also uses <a>.

File: src/shared/components/community/sidebar.tsx [hunk 2]
```diff
@@ -130,9 +130,13 @@ export class Sidebar extends Component<SidebarProps, SidebarState> {
...
           {subscribed == SubscribedType.Pending && (
-            <div class="badge badge-warning mr-2">
+            <a
+              class="btn btn-warning mr-2"
+              href="#"
+              onClick={linkEvent(this, this.handleUnsubscribe)}
+            >
               {i18n.t("subscribe_pending")}
-            </div>
+            </a>
```
Comment (dessalines) [inline src/shared/components/community/sidebar.tsx:139]: This works for now, at some point tho I need to change all these a tags to `<button`s, a tags should only be used for links.

**Review by dessalines — APPROVED** [review]
