### PR TITLE
Dont allow community urls like /c/{id} (fixes #611)

### LINKED ISSUE #611: Communities that are numbers only cannot be accessed via url
### Issue Summary

When you enter a community url, and the commnity id only contains numbers, you get an error.

### Steps to Reproduce

1. click the following link: [https://lemmy.ml/c/195](https://lemmy.ml/c/195)
2. you should get the error: `404: couldnt_find_community`
3. however, if you search for "195" and click on the community link, it works
4. once you're on the community page, if you press "refresh" in the browser, you'll get the same error again

### PR DESCRIPTION
**Pull request by Nutomic**
If the community identifier in url can be interpreted as a valid integer, lemmy-ui considers it as community id, which breaks things if a community has a name with only numbers.

### CODE REVIEW

**Comment by dessalines** [comment]
This is also an issue for usernames, which is in `profile.tsx`. There are a few options:

- Now that fully qualified names are working ( IE /c/announcements@lemmy.ml ), then we can remove the number checks, and also remove numeric ID fetching from the back end completely, and from lemmy-js-client.
- Leave the numeric fetching in place, but add `/username/{number}` and `/community/{number}` in addition to the /c/ and /u/ front end routes. Then when doing that check, use the split[3] == "username" or whatever it is to determine whether it should fetch the number or string version. 

I kinda think the 2nd option is best.

**Comment by Nutomic** [comment]
Removed it from profile.tsx as well. I dont think it makes sense to keep around legacy code because "it might still be used somewhere". That way we will just keep adding more logic that needs to be maintained, with no benefit for anyone.

File: src/shared/components/community/community.tsx [hunk 1]
```diff
@@ -166,17 +166,10 @@ export class Community extends Component<any, State> {
...
-    // It can be /c/main, or /c/1
     let idOrName = pathSplit[2];
-    let id: number;
-    let name_: string;
-    if (isNaN(Number(idOrName))) {
-      name_ = idOrName;
-    } else {
-      id = Number(idOrName);
-    }
+    let name_ = idOrName;
```
Comment (dessalines) [inline src/shared/components/community/community.tsx:170]: You can just do 

`let name_ = pathSplit[2];`

File: src/shared/components/person/profile.tsx [hunk 2]
```diff
@@ -173,21 +163,14 @@ export class Profile extends Component<any, ProfileState> {
       saved_only: view === PersonDetailsView.Saved,
       page,
       limit: fetchLimit,
+      username: pathSplit[2],
     };
     setOptionalAuth(form, req.auth);
-    this.setIdOrName(form, person_id, username);
+    form.username;
```
Comment (dessalines) [inline src/shared/components/person/profile.tsx:169]: This line might have got in by accident.

**Review by dessalines — CHANGES_REQUESTED** [review]

File: src/shared/components/person/profile.tsx [hunk 3]
```diff
@@ -173,21 +164,14 @@ export class Profile extends Component<any, ProfileState> {
       saved_only: view === PersonDetailsView.Saved,
       page,
       limit: fetchLimit,
+      username: username,
     };
     setOptionalAuth(form, req.auth);
-    this.setIdOrName(form, person_id, username);
+    form.username = username;
```
Comment (dessalines) [inline src/shared/components/person/profile.tsx:170]: This line is redundant now since you have the username in the form above.

**Review by dessalines — APPROVED** [review]
