### PR TITLE
Fix community link in modlog title (fixes #2209)

### LINKED ISSUE #2209: Modlog for remote community incorrectly links to local community with the same name
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

The sidebar of https://lemmy.ml/c/microblogmemes@lemmy.world links to https://lemmy.ml/modlog/124413, which contains the modlog of [`!microblogmemes@lemmy.world`](https://lemmy.world/c/microblogmemes).
The modlog page at https://lemmy.ml/modlog/124413 show the following section at the top:
> [/c/microblogmemes ](https://lemmy.ml/c/microblogmemes)Modlog
(There is also a space as part of the link instead of after the link, but that's not in scope for this report.)

This link incorrectly leads to a (in this case non-existing) local community `!microblogmemes@lemmy.ml`.

### Steps to Reproduce

1. Visit remote community, such as https://lemmy.ml/c/microblogmemes@lemmy.world
2. Click modlog link in sidebar
3. Click community name above filters
4. Be on 404 page for non-existing local community

### Technical Details

image

### Lemmy Instance Version

BE: 0.18.5, frontend version is not exposed

### Lemmy Instance URL

https://lemmy.ml

### PR DESCRIPTION
**Pull request by Nutomic**
Screenshot_20250919_145556

### CODE REVIEW

File: src/shared/components/community/community-link.tsx [hunk 1]
```diff
@@ -76,9 +76,9 @@ export function communityLink(
     return { link: `/c/${community.name}` };
   } else {
     const serverStr = `@${hostname(community.ap_id)}`;
-    const link = !realLink
-      ? `/c/${community.name}${serverStr}`
-      : community.ap_id;
+    const link = realLink
+      ? community.ap_id
+      : `/c/${community.name}${serverStr}`;
```
Comment (Nutomic) [inline src/shared/components/community/community-link.tsx:81]: Just flipped these to remove `!` which was confusing.

File: src/shared/components/modlog.tsx [hunk 2]
```diff
@@ -911,9 +911,11 @@ export class Modlog extends Component<ModlogRouteProps, ModlogState> {
               <>
                 <Link
                   className="text-body"
-                  to={`/c/${communityResp.community_view.community.name}`}
+                  to={
+                    communityLink(communityResp.community_view.community).link
+                  }
                 >
-                  /c/{communityResp.community_view.community.name}
+                  {communityLink(communityResp.community_view.community).link}
```
Comment (Nutomic) [inline src/shared/components/modlog.tsx:918]: Dont see any way to create a variable here, and doesnt seem worth the effort making a separate function that is only used once.

Comment (dessalines) [reply src/shared/components/modlog.tsx:918]: That's fine. Its pretty annoying to do a lot of variable manipulation inside react html, and the only way to do it correctly is to extract to a function / component.

But also, you can probably just use `<CommunityLink` here anyway. And if we need to do styling, use props to manipulate that.

Comment (Nutomic) [reply src/shared/components/modlog.tsx:918]: Tried to use that but it looks very strange with different colors and text sizes, and then the "modlog" text with a different style right after it.

Comment (dessalines) [reply src/shared/components/modlog.tsx:918]: Alright, this is fine then.
