### PR TITLE
Fix <hr> being almost invisible

### LINKED ISSUE #533: <hr> hard to see in darkly theme.

### PR DESCRIPTION
**Pull request by ayan4m1**
Before:

Screenshot 2023-06-15 082518

After:

Screenshot 2023-06-15 082435

Two changes:

 * Add `border border-primary` to the `<hr>` but only if it is not the last item in the listing.
 * Add typing information to `this.posts.map()` call

Fixed #533

### CODE REVIEW

File: src/shared/components/post/post-listings.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ export class PostListings extends Component<PostListingsProps, any> {
     return (
       <div>
         {this.posts.length > 0 ? (
-          this.posts.map(post_view => (
+          this.posts.map((post_view: PostView, idx: number) => (
             <>
```
Comment (SleeplessOne1917) [inline src/shared/components/post/post-listings.tsx:72]: Are the explicit types necessary? Typescript should already be able to infer these types if I'm not mistaken.

Comment (ayan4m1) [reply src/shared/components/post/post-listings.tsx:72]: Good point, updated!
