### PR TITLE
Expanded the RegEx to check if the title contains new line caracters. Should fix issue #1962

### LINKED ISSUE #1962: New line in title freezes the webui
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When creating a new post the WebUI "freezes" (The send button spins indefinitely) if the textbox for the new title contains a new line character.

grafik

### Steps to Reproduce

1. Create a new Post
2. Enter a title with multiple lines
3. send

### Technical Details

Windows 10, Firefox 115.0.2 (64-Bit)

### Lemmy Instance Version

0.18.2

### Lemmy Instance URL

https://feddit.de

### PR DESCRIPTION
**Pull request by SomeoneStoleMyNickname**
Should fix the issue #1962.
Also added Comments for clarity.

## Description

Expanded the RegEx in the validTitle helper function. 
Fixes #1962 

### Before
Invalid titles containing a new line character didn't return the correct value

### After
Invalid titles containing a new line character return the right value

### CODE REVIEW

File: src/shared/utils/helpers/valid-title.ts [hunk 1]
```diff
@@ -2,7 +2,14 @@ export default function validTitle(title?: string): boolean {
   // Initial title is null, minimum length is taken care of by textarea's minLength={3}
   if (!title || title.length < 3) return true;
 
-  const regex = new RegExp(/.*\S.*/, "g");
+
+  /*
+    Test if the Title is in a valid format:
+      (?=.*\S.*) checks if the title consits of only whitespace characters
```
Comment (alectrocute) [inline src/shared/utils/helpers/valid-title.ts:8]:
```suggestion
      (?=.*\S.*) checks if the title consists of only whitespace characters
```

**Review by dessalines — COMMENTED** [review]
Also make sure you run `yarn prettier -w src`, since you didn't set up husky.

**Review by dessalines — APPROVED** [review]
