### PR TITLE
Hide NSFW field for create post form, for NSFW communities.

### LINKED ISSUE #2885: Tick the "NSFW" checkbox per default if a user creates a new post in a NSFW community
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I ocassionally get NSFW posts showing up in my timeline that are not tagged NSFW but very graphic in detail. I wondered if people deliberately tag the NSFW posts incorrectly, effectively harming the Fediverse's ability to separate betwen SFW and NSFW posts...

But then I noticed this isn't handled consistently on Lemmy. If I create a post in a NSFW community, it will have the NSFW checkbox ticked per default on lemmynsfw.com. Yet it is un-ticked per default if I do the same from discuss.tchncs.de.

Lemmy seems to work around this by just suppressing posts in the feeds that are non-nsfw but in a nsfw community. I'd argue this doesn't really make sense. It's intransparent and makes that whole checkbox meaningless. If you don't want the posts to appear, you'd force the tag and not work around later.

### Proposed Solution

A good start would be to just have that checkbox ticked by default if someone creates a post in a NSFW community.

### Steps to Reproduce

1. Go to a NSFW community (!nsfw_test@discuss.tchncs.de)
2. click "Create post"
3. result: NSFW checkbox is unticked. If the user now submits the post, it's likely that we get a NSFW post that is not tagged correctly

### Technical Details

Linux, Firefox

### Lemmy Instance Version

0.19.8

### Lemmy Instance URL

* lemmynsfw.com
* discuss.tchncs.de

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #2885

## Description

Hides the NSFW field on create post for NSFW communities.

A back-end PR will also handle making that a default.

## Screenshots

Screenshot_20250107_165941_Kiwi Browser

### CODE REVIEW

File: src/shared/components/home/site-form.tsx [hunk 1]
```diff
@@ -908,6 +909,9 @@ export class SiteForm extends Component<SiteFormProps, SiteFormState> {
 
   handleSiteEnableNsfwChange(i: SiteForm, event: any) {
     i.state.siteForm.enable_nsfw = event.target.checked;
+    if (!event.target.checked) {
+      i.state.siteForm.content_warning = "";
+    }
```
Comment (Nutomic) [inline src/shared/components/home/site-form.tsx:914]: I noticed that `enable_nsfw` is actually unused in the backend and removed it (https://github.com/LemmyNet/lemmy/pull/5311). So it should also be removed here.

**Review by SleeplessOne1917 — APPROVED** [review]

File: src/shared/components/home/site-form.tsx (hunk 1 above)
Comment (dessalines) [reply src/shared/components/home/site-form.tsx:914]: We'll handle that on the next lemmy-js-client types generation. This form field at least just uses a checkbox to show the content warning field.
