### PR TITLE
Fix "show context" (fixes #3496)

### LINKED ISSUE #3496: [0.19] Show context not working properly
### Requirements

- [x] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [x] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [x] It's a single bug. Do not report multiple bugs in one issue.
- [x] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Clicking "show context" on [this page](https://voyager.lemmy.ml/post/413/23#comment-23) but keeps showing the same comment instead of the parent. And after clicking "show context" a few more times, it doesnt do anything. Previously mentioned in https://github.com/LemmyNet/lemmy-ui/pull/3475

Here are the api responses:

https://voyager.lemmy.ml/api/v4/comment/list/slim?post_id=413&parent_id=22&max_depth=8&sort=Hot&type_=All
```json
{
  "comments":[
    {
      "comment":{
        "id":23,
        "creator_id":2,
        "post_id":413,
        "content":"333",
        "removed":false,
        "published_at":"2025-09-25T08:12:41.942137Z",
        "deleted":false,
        "ap_id":"https://voyager.lemmy.ml/comment/23",
        "local":true,
        "path":"0.21.22.23",
        "distinguished":false,
        "language_id":0,
        "score":1,
        "upvotes":1,
        "downvotes":0,
        "child_count":0,
        "report_count":0,
        "unresolved_report_count":0,
        "federation_pending":false,
        "locked":false
      },
      "creator":{
        "id":2,
        "name":"nutomic",
        "published_at":"2025-09-01T10:22:26.064267Z",
        "ap_id":"https://voyager.lemmy.ml/u/nutomic",
        "local":true,
        "deleted":false,
        "bot_account":false,
        "instance_id":1,
        "post_count":4,
        "comment_count":6
      },
      "creator_is_admin":true,
      "can_mod":false,
      "creator_banned":false,
      "creator_is_moderator":true,
      "creator_banned_from_community":false
    },
    {
      "comment":{
        "id":22,
        "creator_id":2,
        "post_id":413,
        "content":"222",
        "removed":false,
        "published_at":"2025-09-25T08:12:40.018956Z",
        "deleted":false,
        "ap_id":"https://voyager.lemmy.ml/comment/22",
        "local":true,
        "path":"0.21.22",
        "distinguished":false,
        "language_id":0,
        "score":1,
        "upvotes":1,
        "downvotes":0,
        "child_count":1,
        "report_count":0,
        "unresolved_report_count":0,
        "federation_pending":false,
        "locked":false
      },
      "creator":{
        "id":2,
        "name":"nutomic",
        "published_at":"2025-09-01T10:22:26.064267Z",
        "ap_id":"https://voyager.lemmy.ml/u/nutomic",
        "local":true,
        "deleted":false,
        "bot_account":false,
        "instance_id":1,
        "post_count":4,
        "comment_count":6
      },
      "creator_is_admin":true,
      "can_mod":false,
      "creator_banned":false,
      "creator_is_moderator":true,
      "creator_banned_from_community":false
    }
  ],
  "next_page":"C16",
  "prev_page":"C17"
}
```
https://voyager.lemmy.ml/api/v4/comment/list/slim?post_id=413&parent_id=21&max_depth=8&sort=Hot&type_=All
```json
{
  "comments":[
    {
      "comment":{
        "id":23,
        "creator_id":2,
        "post_id":413,
        "content":"333",
        "removed":false,
        "published_at":"2025-09-25T08:12:41.942137Z",
        "deleted":false,
        "ap_id":"https://voyager.lemmy.ml/comment/23",
        "local":true,
        "path":"0.21.22.23",
        "distinguished":false,
        "language_id":0,
        "score":1,
        "upvotes":1,
        "downvotes":0,
        "child_count":0,
        "report_count":0,
        "unresolved_report_count":0,
        "federation_pending":false,
        "locked":false
      },
      "creator":{
        "id":2,
        "name":"nutomic",
        "published_at":"2025-09-01T10:22:26.064267Z",
        "ap_id":"https://voyager.lemmy.ml/u/nutomic",
        "local":true,
        "deleted":false,
        "bot_account":false,
        "instance_id":1,
        "post_count":4,
        "comment_count":6
      },
      "creator_is_admin":true,
      "can_mod":false,
      "creator_banned":false,
      "creator_is_moderator":true,
      "creator_banned_from_community":false
    },
    {
      "comment":{
        "id":22,
        "creator_id":2,
        "post_id":413,
        "content":"222",
        "removed":false,
        "published_at":"2025-09-25T08:12:40.018956Z",
        "deleted":false,
        "ap_id":"https://voyager.lemmy.ml/comment/22",
        "local":true,
        "path":"0.21.22",
        "distinguished":false,
        "language_id":0,
        "score":1,
        "upvotes":1,
        "downvotes":0,
        "child_count":1,
        "report_count":0,
        "unresolved_report_count":0,
        "federation_pending":false,
        "locked":false
      },
      "creator":{
        "id":2,
        "name":"nutomic",
        "published_at":"2025-09-01T10:22:26.064267Z",
        "ap_id":"https://voyager.lemmy.ml/u/nutomic",
        "local":true,
        "deleted":false,
        "bot_account":false,
        "instance_id":1,
        "post_count":4,
        "comment_count":6
      },
      "creator_is_admin":true,
      "can_mod":false,
      "creator_banned":false,
      "creator_is_moderator":true,
      "creator_banned_from_community":false
    },
    {
      "comment":{
        "id":21,
        "creator_id":2,
        "post_id":413,
        "content":"111",
        "removed":false,
        "published_at":"2025-09-25T08:12:37.445643Z",
        "deleted":false,
        "ap_id":"https://voyager.lemmy.ml/comment/21",
        "local":true,
        "path":"0.21",
        "distinguished":false,
        "language_id":0,
        "score":1,
        "upvotes":1,
        "downvotes":0,
        "child_count":2,
        "report_count":0,
        "unresolved_report_count":0,
        "federation_pending":false,
        "locked":false
      },
      "creator":{
        "id":2,
        "name":"nutomic",
        "published_at":"2025-09-01T10:22:26.064267Z",
        "ap_id":"https://voyager.lemmy.ml/u/nutomic",
        "local":true,
        "deleted":false,
        "bot_account":false,
        "instance_id":1,
        "post_count":4,
        "comment_count":6
      },
      "creator_is_admin":true,
      "can_mod":false,
      "creator_banned":false,
      "creator_is_moderator":true,
      "creator_banned_from_community":false
    }
  ],
  "next_page":"C15",
  "prev_page":"C17"
}
```

So the responses look correct but the ui is not rendering them properly.

### PR DESCRIPTION
**Pull request by Nutomic**
Seems like lemmy-ui assumes that parent comments are always listed first, but this is not the case anymore. Worth considering to fix this in the backend instead as it may affect other frontends too.

### CODE REVIEW

File: src/shared/utils/app.ts [hunk 1]
```diff
@@ -62,7 +62,8 @@ export function buildCommentsTree(
     ? 0
     : (getDepthFromComment(comments[0].comment) ?? 0);
```
Comment (matc-pub) [inline src/shared/utils/app.ts]: `comments` should already be sorted here.

File: src/shared/utils/app.ts [hunk 2]
```diff
@@ -62,7 +62,8 @@ export function buildCommentsTree(
...
 
-  for (const comment_view of comments) {
+  const comments_sorted = comments.sort((a, b) => a.comment.id - b.comment.id);
```
Comment (matc-pub) [inline src/shared/utils/app.ts]: "This method mutates the array and returns a reference to the same array."

**Review by matc-pub — CHANGES_REQUESTED** [review]
Using `find()` should be faster.

```diff
diff --git a/src/shared/components/post/post.tsx b/src/shared/components/post/post.tsx
index d2807366..bb2eebd0 100644
--- a/src/shared/components/post/post.tsx
+++ b/src/shared/components/post/post.tsx
@@ -997,7 +997,7 @@ export class Post extends Component<PostRouteProps, PostState> {
     if (this.state.commentsRes.state === "success") {
       const comments = this.state.commentsRes.data.comments;
       if (comments.length) {
-        return buildCommentsTree(comments, !!getCommentIdFromProps(this.props));
+        return buildCommentsTree(comments, getCommentIdFromProps(this.props));
       }
     }
     return [];
diff --git a/src/shared/utils/app.ts b/src/shared/utils/app.ts
index c424d77d..3fc51756 100644
--- a/src/shared/utils/app.ts
+++ b/src/shared/utils/app.ts
@@ -26,6 +26,7 @@ import {
   Person,
   CommentSlimView,
   Community,
+  CommentId,
 } from "lemmy-js-client";
 import {
   CommentNodeI,
@@ -56,12 +57,14 @@ import { httpBackendUrl } from "./env";
 
 export function buildCommentsTree(
   comments: CommentSlimView[],
-  parentComment: boolean,
+  parentCommentId?: CommentId,
 ): CommentNodeI[] {
   const map = new Map<number, CommentNodeI>();
+  const parentComment =
+    parentCommentId && comments.find(c => c.comment.id === parentCommentId);
   const depthOffset = !parentComment
     ? 0
-    : (getDepthFromComment(comments[0].comment) ?? 0);
+    : (getDepthFromComment(parentComment.comment) ?? 0);
 
   for (const comment_view of comments) {
     const depthI = getDepthFromComment(comment_view.comment) ?? 0;
@@ -78,7 +81,7 @@ export function buildCommentsTree(
 
   // if its a parent comment fetch, then push the first comment to the top node.
   if (parentComment) {
-    const cNode = map.get(comments[0].comment.id);
+    const cNode = map.get(parentComment.comment.id);
     if (cNode) {
       tree.push(cNode);
     }
```

File: src/shared/utils/app.ts (hunk 2 above)
Comment (Nutomic) [reply src/shared/utils/app.ts]: Fixed

**Comment by Nutomic** [comment]
@matc-pub Thanks for the suggestions. I applied them with some small adjustments.

**Review by matc-pub — APPROVED** [review]

**Review by SleeplessOne1917 — APPROVED** [review]

**Review by dessalines — APPROVED** [review]
