### PR TITLE
Fix missing classes on external link thumbnails with images

### LINKED ISSUE #1693: External link thumbnails with image aren't relative
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

- External link thumbnails with image aren't relative

Screenshot 2023-06-29 at 8 09 00 AM

### Steps to Reproduce

1. Go to https://voyager.lemmy.ml
2. Observe thumbnail with external link image

### Lemmy Instance Version

0.18.1-rc3

### Lemmy Instance URL

https://voyager.lemmy.ml

### PR DESCRIPTION
**Pull request by alectrocute**
Hi all,

In this PR:

- Fix missing classes on external link thumbnails with images
- Resolves #1693 

Thanks!

### CODE REVIEW

File: src/shared/components/post/post-listing.tsx [hunk 1]
```diff
@@ -333,7 +333,7 @@ export class PostListing extends Component<PostListingProps, PostListingState> {
       return (
         <button
           type="button"
-          className="thumbnail rounded overflow-hidden d-inline-block position-relative mb-2 p-0 border-0"
```
Comment (alectrocute) [inline src/shared/components/post/post-listing.tsx:336]: Don't see a need for `mb-2`.

File: src/shared/components/post/post-listing.tsx [hunk 2]
```diff
@@ -348,7 +348,7 @@ export class PostListing extends Component<PostListingProps, PostListingState> {
     } else if (!this.props.hideImage && url && thumbnail && this.imageSrc) {
       return (
         <a
-          className="thumbnail rounded bg-light d-flex justify-content-center"
```
Comment (alectrocute) [inline src/shared/components/post/post-listing.tsx:351]: Crux of the issue here.

**Review by SleeplessOne1917 — APPROVED** [review]
