### PR TITLE
Remove min and max length from password input when using login form

### LINKED ISSUE #2381: [Bug]:  New password length requirements breaks login for users
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

```
lemmy-ui:0.19.1
lemmy:0.19.1
```

In an older version users could register with passwords <10 chars, in the new version frontend code you can only login with 10+ chars. This means users with old shorter passwords cannot login to the board. 

Please add a fix, or a config option to make the password min length shorter so these users may login. Thanks

### Steps to Reproduce

As above.

### Technical Details

As above.

### Version

0.19.1

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Fixes #2381 using @richardARPANET 's suggestion.

Something I noticed working on this is that whitespace is allowed in passwords. This doesn't seem a problem in and of itself, but it's possible to make a password entirely from whitespace. Should this be allowed?

### CODE REVIEW

File: src/shared/components/common/password-input.tsx [hunk 1]
```diff
@@ -99,8 +99,10 @@ class PasswordInput extends Component<PasswordInputProps, PasswordInputState> {
                 onInput={onInput}
                 value={value}
                 required
-                pattern=".{10,60}"
+                pattern=".+"
```
Comment (SleeplessOne1917) [inline src/shared/components/common/password-input.tsx:102]: I changed the pattern since length is all we're checking for and min and max length gives more information to users as to what is wrong than using the pattern.

**Review by dessalines — APPROVED** [review]
