### PR TITLE
Fix indentation for robots and security handler txts.

### LINKED ISSUE #3026: RFC 9116 security.txt generated not according to specification
### Requirements

- [x] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [x] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [x] It's a single bug. Do not report multiple bugs in one issue.
- [x] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Seems like the changes in 1ff4acc0492c52bc1279c79472cd732eb8d384f8 (specifically line https://github.com/LemmyNet/lemmy-ui/commit/1ff4acc0492c52bc1279c79472cd732eb8d384f8#diff-0a78ffa51047f13045854b630d09f1b9cdb7bf5985101d0d8cb481377849ab4aR16) cause the generated security.txt file to have two spaces in front of the 'Expires' field. This makes the file not according to specs and may cause autmatic parsing to fail (which is somewhat the point of having a security.txt file).

Live example: https://feddit.nl/.well-known/security.txt
Security.txt validation: https://internet.nl/site/feddit.nl/3203705/

### Steps to Reproduce

1. Navigate to a lemmy instance, add URL path /.well-known/security.txt

### Technical Details

Not relevant

### Lemmy Instance Version

0.19.10

### Lemmy Instance URL

https://feddit.nl/.well-known/security.txt

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #3026

### CODE REVIEW

File: src/server/handlers/robots-handler.ts [hunk 1]
```diff
@@ -4,17 +4,17 @@ export default async ({ res }: { res: Response }) => {
...
+Disallow: /login_reset
+Disallow: /settings
+Disallow: /create_community
+Disallow: /create_post
+Disallow: /create_private_message
+Disallow: /inbox
+Disallow: /setup
+Disallow: /admin
+Disallow: /password_change
+Disallow: /search/
```
Comment (SleeplessOne1917) [inline src/server/handlers/robots-handler.ts:17]: Should this have a trailing slash?

Comment (dessalines) [reply src/server/handlers/robots-handler.ts:17]: Fixed.

**Review by SleeplessOne1917 — APPROVED** [review]
