### PR TITLE
Fix select dropdowns.

### LINKED ISSUE #4053: Fix community / creator searching in dropdowns
### Requirements

- [x] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [x] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [x] It's a single bug. Do not report multiple bugs in one issue.
- [x] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

These are distorted both visually, and aren't working correctly.

Image

### Steps to Reproduce

1. Try to search in a community 
2. Its distorted, and incorrect

### Technical Details

NA

### Lemmy Instance Version

main

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by dessalines**
- Dropdown searching, and some UI formatting was broken. See below issue for context.
- Fixes #4053

### CODE REVIEW

File: src/shared/components/common/filter-chip-select.tsx [hunk 1]
```diff
@@ -106,8 +106,9 @@ export class FilterChipSelect extends Component<Props, State> {
       if (this.props.onSearch) {
         // From MDN: "This feature is not standardized." and the event type is "A generic Event."
         // Not supported in Firefox and Safari
-        element.addEventListener("search", () => {
-          const searchText: string = element.value;
+        element.addEventListener("search", (e: CustomEvent) => {
+          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment
+          const searchText: string = e.detail.value;
```
Comment (Nutomic) [inline src/shared/components/common/filter-chip-select.tsx]:
```suggestion
          // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
          const searchText = e.detail.value as string;
```

**Review by Nutomic — APPROVED** [review]
