### PR TITLE
Fix leap year issue

### LINKED ISSUE #2441: Cake days are 1 day off on leap years
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

The current implementation:

```ts
import { parseISO, getYear, getDayOfYear } from "date-fns";

export default function isCakeDay(published: string): boolean {
  const createDate = parseISO(published);
  const currentDate = new Date();

  return (
    getDayOfYear(createDate) === getDayOfYear(currentDate) &&
    getYear(createDate) !== getYear(currentDate)
  );
}
```

Unfortunately, `getDayOfYear` counts... well, the day of the year. So on a leap year, this will be 1 day off what is expected. I noticed this as [Feddit.dk claims that it is my cake day today](https://feddit.dk/u/SorteKanin), even though it is actually tomorrow. But of course, 2024 is a leap year, so it's 1 day off because of the 29th of February.

### Steps to Reproduce

Well it's hard to reproduce as you need to find a user with a cake day tomorrow, but it should be easy enough to understand the bug from the code.

### Technical Details

N/A

### Lemmy Instance Version

0.19.3

### Lemmy Instance URL

https://feddit.dk/

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Closes #2441 

Besides fixing the bug listed in the issue, if a user creates their account on February 29th of a leap year, their cake day is March 1st for non leap years.

### CODE REVIEW

File: src/shared/utils/helpers/is-cake-day.ts [hunk 1]
```diff
@@ -1,11 +1,34 @@
-import { parseISO, getYear, getDayOfYear } from "date-fns";
+import { parseISO, getYear, getDayOfYear, isLeapYear } from "date-fns";
+
+const leapDay = getDayOfYear(new Date(2024, 1, 29));
 
 export default function isCakeDay(published: string): boolean {
```
Comment (SleeplessOne1917) [inline src/shared/utils/helpers/is-cake-day.ts:5]: I made sure to test that this behaves as described in the PR description. If we weren't pivoting to a rewritten UI, this would be a prime candidate for unit testing.

**Comment by matc-pub** [comment]
Date constructor docs (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date):
> If any parameter overflows its defined bounds, it "carries over". For example, if a monthIndex greater than 11 is passed in, those months will cause the year to increment; if a minutes greater than 59 is passed in, hours will increment accordingly, etc. Therefore, new Date(1990, 12, 1) will return January 1st, 1991; new Date(2020, 5, 19, 25, 65) will return 2:05 A.M. June 20th, 2020.

`setMonth` and `setFullYear` have similar descriptions in their docs. This also considers leap days in non leap years as first of march:

```typescript
  return (
    isSameDay(currentDate, setYear(createDate, getYear(currentDate))) &&
    !isSameYear(currentDate, createDate)
  );
```

There is also an issue with how Profile displays the date. The same profile can show different dates to users in different timezones. This assertion will fail unless the user is in UTC+0:

```typescript
console.assert(
  format(parseISO("2023-05-11T00:00:00.000Z"), "PPP") ===
    format(parseISO("2023-05-11T23:59:00.000Z"), "PPP"),
);
```
https://github.com/LemmyNet/lemmy-ui/blob/17097ecd34fd65a900825ec488f47a9ccdae839f/src/shared/components/person/profile.tsx#L696-L699

**Comment by SleeplessOne1917** [comment]
Is the first codeblock you shared supposed to be a simpler implementation and/or fix the timezone bug you mentioned? If so, I can change the PR to use that instead.

**Comment by matc-pub** [comment]
Just simpler.

I think this should fix the timezone issue, as long as `published` always starts with `"yyyy-MM-dd"` (the optional `current` date is just for testing):
```typescript
import {
  format,
  getYear,
  isSameDay,
  isSameYear,
  parse,
  setYear,
} from "date-fns";

// Returns a date in local time with the same year, month and day. Ignores the
// source timezone.
export function cakeDate(published: string): Date {
  return parse(published.substring(0, 10), "yyyy-MM-dd", new Date(0));
}

export default function isCakeDay(published: string, current?: Date): boolean {
  const createDate = cakeDate(published);
  const currentDate = current ?? new Date();

  return (
    isSameDay(currentDate, setYear(createDate, getYear(currentDate))) &&
    !isSameYear(currentDate, createDate)
  );
}

console.assert(
  isCakeDay("2023-05-11T00:00:00.000Z", new Date(2024, 4, 11)),
  "basic, early",
);
console.assert(
  isCakeDay("2023-05-11T23:59:00.000Z", new Date(2024, 4, 11)),
  "basic, late",
);

console.assert(
  !isCakeDay("2024-05-11T00:00:00.000Z", new Date(2024, 4, 11)),
  "not today, early",
);
console.assert(
  !isCakeDay("2024-05-11T23:59:00.000Z", new Date(2024, 4, 11)),
  "not today, late",
);

console.assert(
  isCakeDay("2020-02-29T00:00:00.000Z", new Date(2024, 1, 29)),
  "leap day, leap year",
);
console.assert(
  isCakeDay("2020-02-29T00:00:00.000Z", new Date(2025, 2, 1)),
  "leap day, non leap year",
);

console.assert(
  isCakeDay("2023-03-01T00:00:00.000Z", new Date(2024, 2, 1)),
  "first of march, leap year",
);
console.assert(
  isCakeDay("2023-03-01T00:00:00.000Z", new Date(2024, 2, 1)),
  "first of march, non leap year",
);

console.assert(
  isCakeDay("2020-03-01T00:00:00.000Z", new Date(2024, 2, 1)),
  "first of march leap year, leap year",
);
console.assert(
  isCakeDay("2020-03-01T00:00:00.000Z", new Date(2024, 2, 1)),
  "first of march leap year, non leap year",
);

console.assert(
  format(cakeDate("2023-05-11T00:00:00.000Z"), "PPP") ===
    format(cakeDate("2023-05-11T23:59:00.000Z"), "PPP"),
);
console.assert(
  format(cakeDate("2023-05-11T23:59:00.000Z"), "PPP") === "May 11th, 2023",
  format(cakeDate("2023-05-11T23:59:00.000Z"), "PPP"),
);
```

**Comment by dessalines** [comment]
@matc-pub could you open that one up either as a PR to this branch, or to main?

**Review by dessalines — APPROVED** [review]
