### PR TITLE
Fixing CSP for iOS devices. Fixes #669

### LINKED ISSUE #669: login broken in webkit
### Issue Summary

Login does not work in the 16.4 release of lemmy-ui for webkit browsers. ios and osx

### Steps to Reproduce

1. on osx or iphone go to lemmy.ml
2. try to login
3. you can't

### Technical details

Console says something about 'undefined is not an object (evaluating 'this.we.send')'

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: src/server/index.tsx [hunk 1]
```diff
@@ -27,16 +27,15 @@ const [hostname, port] = process.env["LEMMY_UI_HOST"]
...
-// }
+if (!process.env["LEMMY_UI_DEBUG"]) {
+  server.use(function (_req, res, next) {
+    res.setHeader(
+      "Content-Security-Policy",
+      `default-src 'none'; connect-src 'self' ${wsUriBase}; img-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'self'`
+    );
+    next();
+  });
+}
```
Comment (Nutomic) [inline src/server/index.tsx:38]: So this means CSP only runs in prod, not in debug right? Like i said before, i dont like this because we might break things during dev, and not notice until its deployed. Why not simply set a different `connect-src` depending on the debug env var?

Comment (dessalines) [reply src/server/index.tsx:38]: Correct. Eruda can't work with CSP, its remote javascript, so I need a flag to be able to disable it during dev.

Comment (dessalines) [reply src/server/index.tsx:38]: What's sad too is I at least found a good repo that replicates rust Results and Options, but it doesn't deserialize correctly :(

**Comment by makotech222** [comment]
Just want to note, this change breaks websocket connections on local dev testing on Windows machine. I had to revert in order to get it in working condition again. Should we be setting environment variable for 'LEMMY_UI_DEBUG' now?

**Comment by dessalines** [comment]
Yep, please set that for local dev. `export LEMMY_UI_DEBUG=true`
