### PR TITLE
Don't show login toaster upon user settings change

### LINKED ISSUE #1784: When saving settings, "Logged In" toast pops up
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When saving personal settings, a "Logged In" toast pops up.

Screenshot 2023-07-03 at 12 39 48 PM

### Steps to Reproduce

1. Go to settings
2. Save settings
3. See 'Logged In' toast in lower-left corner

### Technical Details

Safari macOS

### Lemmy Instance Version

0.18.1-rc.7

### Lemmy Instance URL

https://beehaw.org

### PR DESCRIPTION
**Pull request by alectrocute**
## Description

- Add `showToast` param to `UserService`'s instance `login` method.
- Resolves #1784.

## Screenshots

Screenshot 2023-07-04 at 8 50 39 AM

### CODE REVIEW

File: src/shared/components/person/settings.tsx [hunk 1]
```diff
@@ -1175,8 +1175,12 @@ export class Settings extends Component<any, SettingsState> {
       ...i.state.saveUserSettingsForm,
       auth: myAuthRequired(),
     });
+
     if (saveRes.state === "success") {
-      UserService.Instance.login(saveRes.data);
+      UserService.Instance.login({
+        res: saveRes.data,
+        showToast: false,
+      });
```
Comment (SleeplessOne1917) [inline src/shared/components/person/settings.tsx:1183]: This works for now, but I always found it odd how the flow for changing settings involves making a call to login. Ideally we'd be able to update the settings without doing that.

**Review by SleeplessOne1917 — APPROVED** [review]

**Review by dessalines — APPROVED** [review]

File: src/shared/components/person/settings.tsx (hunk 1 above)
Comment (dessalines) [reply src/shared/components/person/settings.tsx:1183]: Yeah its def a weird one, should probably be reworked sometime.
