### PR TITLE
Re-add show source for comments

### LINKED ISSUE #2288: View source button on comments is missing.
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

We missed this one.

### Steps to Reproduce

N/A

### Technical Details

N/A

### Lemmy Instance Version

main

### Lemmy Instance URL

https://lemmy.ml

### PR DESCRIPTION
**Pull request by SleeplessOne1917**
Fixes #2288

### CODE REVIEW

**Review by dessalines — APPROVED** [review]
Cool, thx

File: src/shared/components/comment/comment-node.tsx [hunk 1]
```diff
@@ -112,6 +112,13 @@ interface CommentNodeProps {
   onPurgeComment(form: PurgeComment): Promise<void>;
 }
 
+function handleToggleViewSource(i: CommentNode) {
+  i.setState(({ viewSource, ...restPrev }) => ({
+    viewSource: !viewSource,
+    ...restPrev,
```
Comment (dessalines) [inline src/shared/components/comment/comment-node.tsx:118]: Side point but is it really necessary to set the rest of the state always?

Comment (SleeplessOne1917) [reply src/shared/components/comment/comment-node.tsx:118]: I think.  Hard to tell due to inferno's lack of docs.
